config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :departments do
    resources :items 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, except: [:index, :new, :create]

  def index
  #GET	/departments
  @departments = Department.all
  end

  def show
  #GET	/departments/:id
  end

  def new
  #GET	/departments/new
  @department = Department.new
  render partial: "form"
  end

  def edit
  #GET	/departments/:id/edit
  render partial: "form"
  end

  def create
  #POST	/departments
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def update
  #PUT	/departments/:id
    if @department.update(department_params)
      redirect_to department_path(@department.id)
    else
      render :edit
    end
  end

  def destroy
  #DELETE	/departments/:id
    @department.destroy
    redirect_to departments_path
  end

  private
    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_item_path(@department, @item)
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to department_item_path(@department)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department )
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def set_department
      @department = Department.find(params[:department_id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :description)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/departments/_form.html.erb
<div class='container'>
  <h1><%= @department.id ? 'Edit Department' : 'Create a Department' %></h1>
</div>
<hr />
<div class='container'>
<%= form_for @department do |d| %>
  <%= d.label :name %>
  <%= d.text_field :name, required: true, autofocus: true %>
  <%= d.submit %>
<% end %>
</div>
<div class='links'>
  <%= link_to 'Back', departments_path %>
</div>

app/views/departments/index.html.erb
<div class='container'>
  <h1>Click a Department to View Items</h1>
</div>
<div class='container'>
  <ul>
    <% @departments.each do |d| %>
      <li><%= link_to d.name, department_path(d)%></li>
    <% end %>
  </ul>
</div>
<div class='links'>
  <span><%= link_to 'Create a New Department', new_department_path %></span>
</div>

app/views/departments/show.html.erb
<div class='container'>
  <h1><%= @department.name %></h1>
</div>
<hr />
<div class='links'>
  <%=link_to 'View Items', department_items_path(@department) %>
  <br/>
  <%= link_to 'Edit Department', edit_department_path(@department) %>
  <br/>
  <%= link_to 'Delete Department', department_path(@department.id), method: :delete %>
  <br/>
  <%= link_to "Back", departments_path %>
  <br/>
</div>

app/views/items/_form.html.erb
<div class='container'>
  <h1><%= @item.id ? 'Edit item' : 'Create item' %></h1>
</div>
<hr />

<div class='container'>
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>
  <br />
  <%= f.submit %>
<% end %>
</div>
<br/>
<div class='links'>
  <%=link_to 'Back to Item', department_items_path([@department, @item])%>
</div>

app/views/items/index.html.erb
<div class='container'>
  <h1>Click an Item for Details</h1>
</div>
<div class='links'>
  <span><%= link_to 'Create a new Item', new_department_item_path(@department) %></span>
<div>
<div class='container'>
  <ul>
    <% @items.each do |i| %>
      <li><%= link_to i.name, department_item_path(@department, i) %></li>
    <% end %>
  </ul>
</div>
<div class='links'>
  <%= link_to 'Back to Department', department_path(@department) %>
</div>

app/views/items/show.html.erb
<div class='container'>
  <h1><%= @item.name %></h1>
  <p>$<%= @item.price %></p>
  <p><%= @item.description %></p>
  <p id='department'>In department: <%=@department.name %></p>
  <br/>
  <%# <h2>Comments</h2> %>
</div>
<hr />

<div class='links'>
  <%= link_to 'Edit item', edit_department_item_path([@department, @item]) %>
  <br/>
  <%= link_to 'Delete item', [@department, @item], method: :delete %>
  <br/>
  <%= link_to 'Back To All items', department_items_path%>
  <br/>
</div>

app/views/layouts/_navbar.html.erb
<header id = 'nav-bar'>
  <span><%= link_to 'Home', home_path %></span>
  <span><%= link_to 'About', about_path %></span>
  <span><%= link_to 'Departments', root_path%></span>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class='container'>
  <h1>About</h1>
</div>
<div class='container'>
  <h2>Welcome to SumGoodStuff Department Store</h2>
</div>
<div class='container'>
  <p>Founded November 2019</p>
  <p>We have lots of stuff</p>
  <br />
  <p>CEO: Abigail Mitchell</p>
</div>

app/views/static_pages/home.html.erb
<div class='container'>
  <h1>Home</h1>
</div>
<div class='container'>
  <h2>SumGoodStuff</h2>
</div>
<div class='container'>
  <p>Let us help you find good stuff<p>
</div>